version: "3"

services:
    db:
        image: mongo
        ports:
            - 27017:27017
    #    lint:
    #        build:
    #            context: .
    #            dockerfile: ./Dockerfile.dev
    #        #        image: lint
    #        container_name: lint
    #        command: npm run lint
    #    test:
    #        build:
    #            context: .
    #            dockerfile: ./Dockerfile.dev
    #        container_name: test
    #        command: npm run test
    devopment:
        #    image: roundtrip/rt-react
        build:
            context: .
            dockerfile: ./Dockerfile.dev
        container_name: web
        env_file:
            - .env.dev
        environment:
            - NODE_ENV_DOCKER=true
            - DB_USER=yuri
            - DB_URL=mongodb://db/mussia4
        #            - GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
        ports:
            - 4000:4000
            - 5001:5001
            - 5000:5000
            - 4001:4001
            - 7000:7000
            - 7070:7070
        volumes:
            - ./packages/servers/webserver1/src:/app/packages/servers/webserver1/src
        #            - ./packages:/app/packages
        command: npm run start
        #        command: >
        #            bash -c "export GOOGLE_CLIENT_SECRET=$(echo $GOOGLE_CLIENT_SECRET)"
        depends_on:
            - db
