version: "3"
services:
    db:
        image: mongo
        ports:
            - 27017:27017
    #    redis:
    #        image: redis
    #        ports:
    #            - 6379:6379
    #    lint:
    #        image: lint
    #        command: npm run lint
    devopment:
        #    image: roundtrip/rt-react
        build:
            context: .
            dockerfile: ./Dockerfile.dev
        #            args:
        #                - port=8000
        container_name: web
        environment:
            #            - PORT=8000
            - NODE_ENV_DOCKER=true
            - DB_USER=yuri
            - DATABASE_URL=mongodb://db/mussia4
        ports:
            - 4000:4000
            - 4001:4001
            - 7000:7000
            - 7070:7070
        volumes:
            - ./packages:/app/packages
        command: npm run start
        depends_on:
            - db
#            - redis
#            - lint
